dist: xenial
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - "lts/*"
  - "node"
branches:
  only:
    - master
    - /^release\/.*$/
    - develop
script:
  - npx envinfo --preset jest
  - npm link
  - npm run build:server:protos
  - npm run build:client
  - npm test
